project_id = "jckqednygnvhqyfqumav"

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.fetch-stations]
verify_jwt = false